### ISSUE TITLE
The preferences are not reset to their default values after Normandy unenrollment

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/federated-learning-v2-study-addon#13]
[Affected versions]:
- Unbranded Firefox 66.0b14

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]
- Have a new Firefox profile created.
- You are enrolled in the experiment through Normandy.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Navigate to "about:studies" page.
3. Click the "Remove" button specific to the experiment.
4. Navigate to "about:config" page.
5. Observe that the following pref has been restored to its default value: _places.frecency.firstBucketCutoff_.

[Expected result]:
- The pref is set to its default value.

[Actual result]:
- The pref value remains modified.

[Notes]:
- This is also reproducible when disabling the recipe from Normandy stage server.
- This is reproducible with all the branches of the experiment.
- Here is a screen recording of the issue:

![prefs](https://user-images.githubusercontent.com/26000308/54432613-603c1d00-4732-11e9-8f27-89446e52c516.gif)

**Comment by motin** [comment]
Thanks for checking this. We will make sure to rely on expiration for proper preference clean-up for this study.

**Comment by motin** [comment]
@SoftVision-CarmenFat please re-test this with the v2.1.4 - found in the artifacts section of https://circleci.com/gh/mozilla/federated-learning-v2-study-addon/22 - Direct link: https://22-168424761-gh.circle-artifacts.com/0/dist/federated_learning_awesome_bar-2.1.4.zip

**Comment by SoftVision-CarmenFat** [comment]
- Re-tested this with the latest 2.1.4 version and I can confirm that the issue is no longer reproducible.
- After opting out from the experiment ("Remove" button from "about:studies" page) or after disabling the recipe from Normandy stage server, the _"places.frecency.firstBucketCutoff"_ pref is reset to its default value.
