### ISSUE TITLE
Need to upload frecencyPings all the time

### ISSUE THREAD

**Issue by crankycoder** [mozilla/federated-learning-v2-study-addon#15]
@motin After reviewing the ETL job - we missed something on the client side.  The addon needs to submit frecency pings for all branches as we need that data to do the analysis for the effectiveness of the branch.  

The ETL job will discard the pings so they won't be taken into consideration for training.

https://github.com/mozilla/federated-learning-v2-study-addon/blob/1d747e76a3e42b1ba3263e9a0f360f722a3eea63/src/feature.js#L25

https://github.com/mozilla/federated-learning-v2-study-addon/blob/1d747e76a3e42b1ba3263e9a0f360f722a3eea63/src/feature.js#L33

**Comment by motin** [comment]
Closing this since pings for analysis are already being sent. See https://github.com/mozilla/federated-learning-v2-study-addon/pull/16#issuecomment-477359949
