### ISSUE TITLE
Improve the user-facing add-on description

### ISSUE THREAD

**Issue by motin** [mozilla/federated-learning-v2-study-addon#3]
Follow-up of https://github.com/florian/federated-learning-addon/issues/15

**Comment by mlopatka** [comment]
here's a proposed public-facing textual description for this study.

> A Firefox add-on study testing the application of federated learning to train our search suggestions algorithm without collecting specific user search data. We are trying out new ways of combining frequency and recency to improve the overall experience when using the Firefox awesomebar.

**Comment by motin** [comment]
Closed in 3563885
Nit: Added "Awesome Bar" instead of "awesomebar". Btw, the survey url uses the expression "URL bar"
