### ISSUE TITLE
The mid study survey is launched even though scheduling the survey pref to 1000 days before expiration

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/federated-learning-v2-study-addon#9]
[Affected versions]:
- Unbranded Firefox 66.0b14

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]
- Have a new Firefox profile created.
- Have the following pref set: "extensions.federated-learning-v2_shield_mozilla_org.test.surveyDaysFromExpiration" to 1000.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Drag and drop the [.xpi](https://bugzilla.mozilla.org/show_bug.cgi?id=1532217#c6) in "about:addons" page.
3. Click "Add"&"OK" buttons from the doorhanger.
4. Open a new tab and search for a string using the address bar (e.g. "tickets").
5. Repeat step 4 and wait for 5 seconds.
6. Observe what happens next.

[Expected result]:
- Nothing happens, the mid study survey is not launched.

[Actual result]:
- The mid study survey is launched in a new tab.

[Notes]:
- This is reproducible with all branches.
- Here is a screen recording of the issue:

![expire survey](https://user-images.githubusercontent.com/26000308/54218313-02bb8c80-44f6-11e9-9534-cc53f53f01bf.gif)

**Comment by motin** [comment]
This is expected. A large value makes the mid-survey period start in the past.

**Comment by SoftVision-CarmenFat** [comment]
Are you sure about this? The Test Plan states the opposite :)

![1000 expire](https://user-images.githubusercontent.com/26000308/54347531-da47a580-464f-11e9-8392-e30d95824a1a.jpg)

**Comment by motin** [comment]
Thanks @SoftVision-CarmenFat, you found a bug in the test plan :) It is now corrected.
